name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch Tags
        run: |
          git fetch --prune --tags ||:
      - name: Setup system dependencies
        run: sudo apt-get install cargo rustc sfnt2woff-zopfli ttfautohint woff2 zsh
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Setup Python dependencies
        run: pip install -r requirements.txt
      - name: Configure
        run: |
          ./bootstrap.sh
          ./configure
          echo ::set-env name=VERSION::$(./build-aux/git-version-gen .tarball-version)
          echo ::set-env name=MAKEFLAGS::-j$(nproc) -Otarget
      - name: Build
        run: |
          make dist
          echo ::set-env name=ISRELEASETAG::$(grep -Pqx '\d+\.\d+\.\d+' .version && echo true || echo false)
      - name: Upload Artifacts
        if: ${{ env.ISRELEASETAG == 'false' }}
        uses: actions/upload-artifact@v2
        with:
          name: fontship-${{ env.VERSION }}
          path: fontship*-${{ env.VERSION }}.zip
      - name: Publish Release
        if: ${{ (env.ISRELEASETAG == 'true' && contains(github.ref, 'refs/tags/v')) }}
        uses: softprops/action-gh-release@v0.1.5
        with:
          body_path: fontship-${{ env.VERSION }}.md
          files: |
            fontship-${{ env.VERSION }}.zip
            fontship-${{ env.VERSION }}.tar.xz
        env:
          GITHUB_TOKEN: ${{ github.token }}
