name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch Tags
        run: |
          git fetch --prune --tags ||:
      - name: Setup system dependencies
        run: sudo apt-get install fontmake fonttools libgit2-dev python3-pip psautohint python3 python3-pygit2 sfnt2woff-zopfli ttfautohint woff2 zsh
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-build-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup Python dependencies
        run: pip install font-v gftools
      - name: Configure
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./bootstrap.sh
          ./configure
          echo ::set-env name=VERSION::$(./build-aux/git-version-gen .tarball-version)
          echo ::set-env name=MAKEFLAGS::-j$(nproc) -Otarget
      - name: Build
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          make dist
          echo ::set-env name=ISRELEASETAG::$(grep -Pqx '\d+\.\d+\.\d+' .version && echo true || echo false)
      - name: Upload Artifacts
        if: ${{ env.ISRELEASETAG == 'false' }}
        uses: actions/upload-artifact@v2
        with:
          name: fontship-${{ env.VERSION }}
          path: fontship*-${{ env.VERSION }}.zip
      - name: Publish Release
        if: ${{ (env.ISRELEASETAG == 'true' && contains(github.ref, 'refs/tags/v')) }}
        uses: softprops/action-gh-release@v0.1.5
        with:
          body_path: fontship-${{ env.VERSION }}.md
          files: |
            fontship-${{ env.VERSION }}.zip
            fontship-${{ env.VERSION }}.tar.xz
        env:
          GITHUB_TOKEN: ${{ github.token }}
