name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - latest
      - v*

jobs:

  ghcr:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --prune --tags ||:
      - name: Setup system dependencies
        run: |
          sudo apt-get install autoconf-archive
      - name: Configure
        run: |
          echo "REF=${GITHUB_REF##refs/*/}" >> $GITHUB_ENV
          ./bootstrap.sh
          ./configure --without-{bash,fish,zsh}-completion-dir --disable-dependency-checks
      - name: Publish Docker Image to GH Pakcages
        run: |
          make docker-build-push
        env:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_REPO: ${{ github.repository }}
          DOCKER_TAG: ${{ env.REF }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PAT: ${{ secrets.CR_FONTSHIP }}
