name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch Tags
        run: git fetch --prune --tags
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: theleagueof/fontship/fontship
          tag_with_ref: true
