name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch Tags
        run: git fetch --prune --tags
      - name: Setup system dependencies
        run: sudo apt-get install sfnt2woff-zopfli ttfautohint zsh
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Setup Python dependencies
        run: pip install -r requirements.txt
      - name: Build Source
        run: |
          ./bootstrap.sh
          ./configure
          make dist
      - name: Get Build Info
        run: |
          echo ::set-env name=VERSION::$(./build-aux/git-version-gen .tarball-version)
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            fontship-${{ env.VERSION }}.zip
            fontship-${{ env.VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
