name: Versioning

on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: true
